# Generated by Django 5.1 on 2024-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cooking_method", models.CharField(max_length=1000)),
                ("cuisine", models.CharField(max_length=1000)),
                ("image", models.CharField(max_length=1000)),
                ("ingredients", models.CharField(max_length=1000)),
                ("prep_time", models.CharField(max_length=1000)),
                ("recipe_name", models.CharField(max_length=1000)),
                ("serves", models.CharField(max_length=1000)),
                ("tags", models.CharField(max_length=1000)),
            ],
        ),
    ]
