# Generated by Django 5.1 on 2026-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cooking_method', models.CharField(max_length=1000)),
                ('cuisine', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('ingredients', models.CharField(max_length=1000)),
                ('prep_time', models.CharField(max_length=1000)),
                ('recipe_name', models.CharField(max_length=1000)),
                ('serves', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
    ]
